"""
This type stub file was generated by pyright.
"""

MESSAGES = ...
def initialize_localities(): # -> None:
    """Load all custom msg files."""
    ...

class LocaleMsgs:
    """A helper class to allow loading the library message catalog
    without having to package library resources which can cause
    problems with creating distributable applications with some
    packagers."""
    def __init__(self, locale, *msgs) -> None:
        ...
    
    def initialize(self): # -> None:
        """Initialize this locale in the MessageCatalog"""
        ...
    


