"""
This type stub file was generated by pyright.
"""

from ttkbootstrap.style import Bootstyle, Style
from ttkbootstrap.widgets import *
from ttkbootstrap.window import Toplevel, Window
from tkinter.scrolledtext import ScrolledText
from tkinter import BooleanVar, Canvas, DoubleVar, IntVar, Menu, PhotoImage, StringVar, Text, Variable

