"""
This type stub file was generated by pyright.
"""

import ttkbootstrap as ttk
from ttkbootstrap.constants import *

"""
    This module contains various custom scrolling widgets, including 
    `ScrolledText` and `ScrolledFrame`.
"""
class ScrolledText(ttk.Frame):
    """A text widget with optional vertical and horizontal scrollbars.
    Setting `autohide=True` will cause the scrollbars to hide when the
    mouse is not over the widget. The vertical scrollbar is on by
    default, but can be turned off. The horizontal scrollbar can be
    enabled by setting `vbar=True`.

    This widget is identical in configuration to the `Text` widget other
    than the scrolling frame. https://tcl.tk/man/tcl8.6/TkCmd/text.htm

    ![scrolled text](../../../assets/scrolled/scrolledtext.gif)

    Examples:

        ```python
        import ttkbootstrap as ttk
        from ttkbootstrap.constants import *
        from ttkbootstrap.scrolled import ScrolledText

        app = ttk.Window()

        # scrolled text with autohide vertical scrollbar
        st = ScrolledText(app, padding=5, height=10, autohide=True)
        st.pack(fill=BOTH, expand=YES)

        # add text
        st.insert(END, 'Insert your text here.')

        app.mainloop()
        ```
    """
    def __init__(self, master=..., padding=..., bootstyle=..., autohide=..., vbar=..., hbar=..., **kwargs) -> None:
        """
        Parameters:

            master (Widget):
                The parent widget.

            padding (int):
                The amount of empty space to create on the outside of
                the widget.

            bootstyle (str):
                A style keyword used to set the color and style of the
                vertical scrollbar. Available options include -> primary,
                secondary, success, info, warning, danger, dark, light.

            vbar (bool):
                A vertical scrollbar is shown when **True** (default).

            hbar (bool):
                A horizontal scrollbar is shown when **True**. Turning
                on this scrollbar will also set `wrap="none"`. This
                scrollbar is _off_ by default.

            autohide (bool):
                When **True**, the scrollbars will hide when the mouse
                is not within the frame bbox.

            **kwargs (Dict[str, Any]):
                Other keyword arguments passed to the `Text` widget.
        """
        ...
    
    @property
    def text(self): # -> Text:
        """Returns the internal text object"""
        ...
    
    @property
    def hbar(self): # -> Scrollbar | None:
        """Returns the internal horizontal scrollbar"""
        ...
    
    @property
    def vbar(self): # -> Scrollbar | None:
        """Returns the internal vertical scrollbar"""
        ...
    
    def hide_scrollbars(self, *_): # -> None:
        """Hide the scrollbars."""
        ...
    
    def show_scrollbars(self, *_): # -> None:
        """Show the scrollbars."""
        ...
    
    def autohide_scrollbar(self, *_): # -> None:
        """Show the scrollbars when the mouse enters the widget frame,
        and hide when it leaves the frame."""
        ...
    


class ScrolledFrame(ttk.Frame):
    """A widget container with a vertical scrollbar.

    The ScrolledFrame fills the width of its container. The height is
    either set explicitly or is determined by the content frame's
    contents.

    This widget behaves mostly like a normal frame other than the
    exceptions stated already. Another exception is when packing it
    into a Notebook or Panedwindow. In this case, you'll need to add
    the container instead of the content frame. For example,
    `mynotebook.add(myscrolledframe.container)`.

    The scrollbar has an autohide feature that can be turned on by
    setting `autohide=True`.

    Examples:

        ```python
        import ttkbootstrap as ttk
        from ttkbootstrap.constants import *
        from ttkbootstrap.scrolled import ScrolledFrame

        app = ttk.Window()

        sf = ScrolledFrame(app, autohide=True)
        sf.pack(fill=BOTH, expand=YES, padx=10, pady=10)

        # add a large number of checkbuttons into the scrolled frame
        for x in range(20):
            ttk.Checkbutton(sf, text=f"Checkbutton {x}").pack(anchor=W)

        app.mainloop()
        ```"""
    def __init__(self, master=..., padding=..., bootstyle=..., autohide=..., height=..., width=..., scrollheight=..., **kwargs) -> None:
        """
        Parameters:

            master (Widget):
                The parent widget.

            padding (int):
                The amount of empty space to create on the outside of
                the widget.

            bootstyle (str):
                A style keyword used to set the color and style of the
                vertical scrollbar. Available options include -> primary,
                secondary, success, info, warning, danger, dark, light.

            autohide (bool):
                When **True**, the scrollbars will hide when the mouse
                is not within the frame bbox.

            height (int):
                The height of the container frame in screen units.

            width (int):
                The width of the container frame in screen units.

            scrollheight (int):
                The height of the content frame in screen units. If None,
                the height is determined by the frame contents.

            **kwargs (Dict[str, Any]):
                Other keyword arguments passed to the content frame.
        """
        ...
    
    def yview(self, *args): # -> None:
        """Update the vertical position of the content frame within the
        container.

        Parameters:

            *args (List[Any, ...]):
                Optional arguments passed to yview in order to move the
                content frame within the container frame.
        """
        ...
    
    def yview_moveto(self, fraction: float): # -> None:
        """Update the vertical position of the content frame within the
        container.

        Parameters:

            fraction (float):
                The relative position of the content frame within the
                container.
        """
        ...
    
    def yview_scroll(self, number: int, what: str): # -> None:
        """Update the vertical position of the content frame within the
        container.

        Parameters:

            number (int):
                The amount by which the content frame will be moved
                within the container frame by 'what' units.

            what (str):
                The type of units by which the number is to be interpeted.
                This parameter is currently not used and is assumed to be
                'units'.
        """
        ...
    
    def enable_scrolling(self): # -> None:
        """Enable mousewheel scrolling on the frame and all of its
        children."""
        ...
    
    def disable_scrolling(self): # -> None:
        """Disable mousewheel scrolling on the frame and all of its
        children."""
        ...
    
    def hide_scrollbars(self): # -> None:
        """Hide the scrollbars."""
        ...
    
    def show_scrollbars(self): # -> None:
        """Show the scrollbars."""
        ...
    
    def autohide_scrollbar(self): # -> None:
        """Toggle the autohide funtionality. Show the scrollbars when
        the mouse enters the widget frame, and hide when it leaves the
        frame."""
        ...
    
    def destroy(self): # -> None:
        ...
    


